/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/Page/Kings/cnps/Button.vue')['default']
    ChangeName: typeof import('./src/Page/Kings/cnps/ChangeName.vue')['default']
    ChangePlace: typeof import('./src/Page/Kings/cnps/ChangePlace.vue')['default']
    Code: typeof import('./src/components/Code.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./src/components/Header.vue')['default']
    Kings: typeof import('./src/Page/Kings/index.vue')['default']
    Learn: typeof import('./src/Page/Learn/index.vue')['default']
    Main: typeof import('./src/Page/Main/index.vue')['default']
    Means: typeof import('./src/Page/Means/index.vue')['default']
    Movies: typeof import('./src/Page/Movies/index.vue')['default']
    Pang: typeof import('./src/Page/Pang/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Utils: typeof import('./src/Page/Utils/index.vue')['default']
  }
}
